namespace QuietNoize.SimpleSOStaticAccess.Editor
{
#if UNITY_EDITOR
    using QuietNoize.SimpleSOStaticAccess;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Reflection;
    using System.Linq;
    using System.Text;
    using System;
    using UnityEditor;
    using UnityEngine;

    /// <summary>
    /// Generates C# static wrapper code from a StaticDataSO using reflection.
    /// Produces compile-time accessors for Unity-serialized fields.
    /// </summary>
    public static class StaticDataCodeBuilder
    {
        #region Core API
        /// <summary>
        /// Entry point for generating wrapper code from a StaticDataSO context.
        /// Combines header, using directives, and generated field accessors.
        /// </summary>
        public static string GetCode(StaticDataGenerationContext ctx)
        {
            if (ctx.Source == null)
            {
                Debug.LogError("[StaticDataCodeBuilder] Source StaticDataSO is null.");
                return string.Empty;
            }

            if (string.IsNullOrWhiteSpace(ctx.Settings.WrapperClassName))
            {
                Debug.LogError("[StaticDataCodeBuilder] WrapperClassName is empty.");
                return string.Empty;
            }

            var sb = new StringBuilder();

            sb.AppendLine(GenerateHeader(ctx.Source));
            sb.AppendLine();

            var type = ctx.Source.GetType();
            var fields = GetAllFields(type);

            sb.AppendLine(GenerateBody(ctx, fields));

            return sb.ToString();
        }

        /// <summary>
        /// Collects all Unity-serializable fields from type hierarchy.
        /// Includes public fields and fields marked with [SerializeField].
        /// Excludes internal generator settings.
        /// </summary>
        private static string GenerateHeader(StaticDataSO so)
        {
            return
        $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by QuietNoize.SimpleSOStaticAccess
//
//     Source: {so.name} ({so.GetType().Name})
//
// </auto-generated>
//------------------------------------------------------------------------------";
        }

        private static string GenerateBody(StaticDataGenerationContext ctx, FieldInfo[] fields)
        {
            if (fields == null || fields.Length == 0)
            {
                Debug.LogWarning($"[StaticDataCodeBuilder] No serialized fields found in {ctx.Source.name}");
            }

            string usings = WriteUsings(fields, string.IsNullOrEmpty(ctx.Settings.WrapperCodeNamespace) ? 0 : 1);
            string fieldsCode = WriteSerializedFields(fields, ctx.Source, string.IsNullOrEmpty(ctx.Settings.WrapperCodeNamespace) ? 1 : 2);

            if (string.IsNullOrEmpty(ctx.Settings.WrapperCodeNamespace))
            {
                return
        $@"{usings}

public static class {ctx.Settings.WrapperClassName}
{{
{fieldsCode}
}}";
            }

            return
        $@"namespace {ctx.Settings.WrapperCodeNamespace}
{{
{usings}

    public static class {ctx.Settings.WrapperClassName}
    {{
{fieldsCode}
    }}
}}";
        }
        #endregion

        #region Reflection
        private static FieldInfo[] GetAllFields(Type type)
        {
            var flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            var fields = new List<FieldInfo>();

            while (type != null && type != typeof(object))
            {
                foreach (var field in type.GetFields(flags))
                {
                    if (field == null)
                        continue;

                    if (field.FieldType == null)
                        continue;

                    bool isSerialized =
                        field.IsPublic ||
                        field.GetCustomAttribute<SerializeField>() != null;

                    if (!isSerialized)
                        continue;

                    if (field.FieldType == typeof(StaticDataCodegenSettings))
                        continue;

                    fields.Add(field);
                }

                type = type.BaseType;
            }

            return fields.ToArray();
        }
        #endregion

        #region Code Generation
        private static string WriteUsings(FieldInfo[] fields, int indentLevel)
        {
            var indent = new string(' ', indentLevel * 4);
            var namespaces = new HashSet<string> { "UnityEngine" };

            foreach (var field in fields)
            {
                var ns = field.FieldType.Namespace;

                if (!string.IsNullOrEmpty(ns))
                    namespaces.Add(ns);
            }

            var lines = namespaces
                .OrderBy(n => n)
                .Select(ns => $"{indent}using {ns};");

            return string.Join("\n", lines);
        }

        private static string WriteSerializedFields(FieldInfo[] fields, StaticDataSO so, int indentLevel)
        {
            var indent = new string(' ', indentLevel * 4);
            var lines = new List<string>();

            foreach (var field in fields)
            {
                var typeName = FormatTypeName(field.FieldType);
                string fieldName = FormatFieldName(field.Name);

                if (string.IsNullOrEmpty(fieldName))
                {
                    Debug.LogError(
                        $"[StaticDataCodeBuilder] Field name became empty after formatting. " +
                        $"Original: '{field.Name}', Type: {typeName}"
                    );
                    continue;
                }

                var value = field.GetValue(so);

                lines.Add(
                    $"{indent}public static {typeName} {fieldName} => {FormatValue(field.FieldType, value, typeName)};"
                );
            }

            return string.Join("\n", lines);
        }
        #endregion

        #region Naming & Formatting
        /// <summary>
        /// Converts System.Type into C# type string representation for generated code.
        /// </summary>
        private static string FormatTypeName(Type fieldType)
        {
            if (fieldType == null)
                return "void";

            if (fieldType == typeof(int)) return "int";
            if (fieldType == typeof(float)) return "float";
            if (fieldType == typeof(bool)) return "bool";
            if (fieldType == typeof(string)) return "string";
            if (fieldType == typeof(double)) return "double";
            if (fieldType == typeof(byte)) return "byte";
            if (fieldType == typeof(long)) return "long";
            if (fieldType == typeof(short)) return "short";
            if (fieldType == typeof(uint)) return "uint";
            if (fieldType == typeof(ulong)) return "ulong";
            if (fieldType == typeof(ushort)) return "ushort";
            if (fieldType == typeof(char)) return "char";
            if (fieldType == typeof(object)) return "object";

            if (Nullable.GetUnderlyingType(fieldType) is Type nullableType)
            {
                return $"{FormatTypeName(nullableType)}?";
            }

            if (fieldType.IsArray)
            {
                return $"{FormatTypeName(fieldType.GetElementType())}[]";
            }

            if (fieldType.IsGenericType)
            {
                var genericDef = fieldType.GetGenericTypeDefinition();
                var name = genericDef.Name;
                name = name.Substring(0, name.IndexOf('`'));

                var args = fieldType.GetGenericArguments()
                    .Select(FormatTypeName);

                return $"{name}<{string.Join(", ", args)}>";
            }

            if (fieldType.IsNested)
            {
                return $"{fieldType.DeclaringType.Name}.{fieldType.Name}";
            }

            return fieldType.Name;
        }

        private static string FormatFieldName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                Debug.LogWarning("[StaticDataCodeBuilder] Empty field name detected.");
                return string.Empty;
            }

            name = name.TrimStart('_');

            if (string.IsNullOrEmpty(name))
            {
                Debug.LogWarning("[StaticDataCodeBuilder] Field name became empty after trimming.");
                return string.Empty;
            }

            if (name.StartsWith("m_")) name = name.Substring(2);
            else if (name.StartsWith("s_")) name = name.Substring(2);

            if (string.IsNullOrEmpty(name))
                return string.Empty;

            return char.ToLowerInvariant(name[0]) + name.Substring(1);
        }

        /// <summary>
        /// Converts a field value into valid C# code representation.
        /// Handles primitives, enums, lists, and Unity-serializable objects.
        /// </summary>
        private static string FormatValue(Type type, object value, string typeName)
        {
            // -------------------------
            // Primitive types
            // -------------------------
            if (type == typeof(int))
                return ((int)value).ToString();

            if (type == typeof(float))
                return ((float)value).ToString(CultureInfo.InvariantCulture) + "f";

            if (type == typeof(double))
                return ((double)value).ToString(CultureInfo.InvariantCulture);

            if (type == typeof(bool))
                return ((bool)value) ? "true" : "false";

            if (type == typeof(string))
                return $"\"{Escape(value.ToString())}\"";

            if (type == typeof(long))
                return ((long)value).ToString() + "L";

            // -------------------------
            // Enum types
            // -------------------------
            if (type.IsEnum)
                return $"{typeName}.{value}";

            // -------------------------
            // List<T> handling via wrapper + JsonUtility
            // -------------------------
            bool isList = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>);
            if (isList)
            {
                if (value == null)
                {
                    return "null";
                }

                try
                {
                    Type elementType = type.GetGenericArguments()[0];

                    var wrapperType = typeof(ListWrapper<>).MakeGenericType(elementType);
                    var wrapper = Activator.CreateInstance(wrapperType, value);

                    return $"JsonUtility.FromJson<QuietNoize.SimpleSOStaticAccess.ListWrapper<{FormatTypeName(elementType)}>>(\"{ToJson(wrapper)}\").items";
                }
                catch (Exception e)
                {
                    Debug.LogError($"[StaticDataCodeBuilder] Failed to serialize list: {e}");
                    return "null";
                }
            }

            // -------------------------
            // Complex / custom types
            // (everything goes through JsonUtility)
            // -------------------------
            return $"JsonUtility.FromJson<{typeName}>(\"{ToJson(value)}\")";
        }

        private static string Escape(string s)
        {
            return s
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r");
        }
        #endregion

        #region Helpers
        private static string ToJson(object value)
        {
            string json = JsonUtility.ToJson(value);
            string escaped = Escape(json);

            return escaped;
        }
        #endregion
    }
#endif
}
